# description du workflow :
# - on push sur la branche dev uniquement
# - le workflow est déclenché
# - on installe les dépendances
# - on lance les tests
# - si les tests passent, on fast-forward dev onto main
# - on push main sur le repo
# - si les tests ne passent pas, create branche failure/<n° unique>
# - on push failure/<n° unique> sur le repo
# - git reset dev HEAD~1
# - on push dev sur le repo

name: Ouais

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Fast-forward dev onto main
      run: |
        git checkout main
        git pull
        git merge dev
        git push

    - name: Push main on repo
      run: |
        git push

    - name: Create failure branch
      run: |
        git checkout -b failure/$(date +%s)
        git push

    - name: Reset dev
      run: |
        git checkout dev
        git reset HEAD~1
        git push


