name: Test et Merge Automatique

on:
 push:
    branches:
      - dev

jobs:
 build-and-test:
    runs-on: ubuntu-latest
    outputs:
      test-success: ${{ job.status == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - name: Mise en place de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test avec pytest
        run: pytest

 merge-to-main-or-failure:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Merge vers main ou failure
        uses: actions/github-script@v3
        with:
          script: |
            const testSuccess = ${{ needs.build-and-test.outputs.test-success }};
            
            if (testSuccess == 'true') {
              await github.rest.repos.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: 'main',
                head: 'dev'
              });
              console.log('Les tests ont réussi. Merge vers main effectué.');
            } else {
              await github.rest.repos.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: 'failure',
                head: 'dev'
              });
              console.log('Les tests ont échoué. Merge vers failure effectué.');
            }